apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: voting-app-pod
  template:
    metadata: 
        labels: 
            app: demo-voting-app
            name: voting-app-pod
        name: voting-app-pod
    spec: 
        containers: 
            - 
            image: docker/example-voting-app-vote
            name: voting-app
            ports: 
                - 
                containerPort: 80