apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: worker-app-pod
  template:
    metadata: 
      labels: 
        app: demo-voting-app
        name: worker-app-pod
      name: worker-app-pod
    spec: 
      containers: 
        - 
          image: docker/example-voting-app-worker
          name: worker-app